<html>
<head>
	<title>Doxen</title>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script type="text/javascript"></script>
</head>
<body>
	<div id="login">
	
	<input type="text" id="username" />
	<input type="text" id="password" />
	<input type="submit" id="login" />
		
	</div>
	<script type="text/javascript">
	$(document).ready(function() {
	});
	</script>
</body>
</html>

